%rebase('base.tpl', Page_Title='Index')
<h1>Краткий словарь тестировщика</h1>

<div dir="ltr" style="text-align: left;" trbidi="on"><div style="color: red;">
<a name="more"></a></div><br>
<br>
<div style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>A</b></span></span><br>
<ul style="color: black; text-align: left;"><li style="color: black; font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>acceptance of certification test - </b>тест сдачи<b>&nbsp;</b></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>approval pending - </b>ожидание утверждения</span></span><b>&nbsp;</b></span></span></li>
<li style="color: black;"><b><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;">approved - </span></span></b><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;">утверждено</span></span></li>
</ul><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>B</b></span></span><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>&nbsp;</b></span></span><br>
<ul style="color: black; text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>back-end</b></span></span> <span style="font-family: Verdana,sans-serif;"><span style="font-size: small;">- это ПО и данные, находящиеся за фасадом фронт-энда: HTML-код</span></span><span style="font-family: Verdana,sans-serif;"> веб-страницы, код приложения и т.д.</span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif;"><b>beta testers - </b>бета-тестировщики </span></li>
<li style="color: black;"><b><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;">bug</span></span></b><b style="font-family: Verdana,sans-serif;">(баг) - </b><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;">отклонение фактического результата (actual result) от ожидаемого результата (expected result)</span></span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif; font-size: small;"><b><span lang="EN-US" style="line-height: 115%;">Bug Tracking System</span></b></span><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"> - баг-трекинговая система</span></span></li>
</ul><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b> </b></span></span></div><div style="color: black;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;">С</span></span></b></span></span></div><ul style="color: black; text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>code inspection - </b>инспекция кода</span></span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>conditions</b> - условия</span></span></span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>CYA (cover your ass)</b> - прикрыть свою спину:)&nbsp;</span></span></span></li>
</ul><div style="color: black;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;">D</span></span></b></span></span></span><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="color: black; font-family: Verdana,sans-serif;"><b><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-size: small;">&nbsp;</span></span></span></b></span></span></span><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="color: black; font-family: Verdana,sans-serif;"><b><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-size: small;"></span></span></span></b></span></span></span><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="color: black; font-family: Verdana,sans-serif;"><b style="color: black;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-size: small;"> </span></span></span></b></span></span></span><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="color: black; font-family: Verdana,sans-serif;"><b style="color: black;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-size: small;">&nbsp;</span></span></span></b></span></span></span><br>
<ul style="text-align: left;"><li><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="color: black; font-family: Verdana,sans-serif;"><b style="color: black;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-size: small;">draft -</span></span></span></b><span style="color: black; font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-size: small;"> черновик&nbsp;</span></span></span><span style="color: black; font-family: Verdana,sans-serif;"><span style="font-size: large;"> </span></span><span style="color: black;">&nbsp;</span></span><b><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"> </span></span></b></span></span></li>
</ul></div><ul style="color: black; text-align: left;"></ul><div style="color: black;"><div><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b><span style="font-size: large;"> </span><span style="font-size: large;">E</span></b></span></span><br>
<ul style="text-align: left;"><li><span style="color: black; font-family: Verdana,sans-serif;"><span style="font-size: small;"><b><span style="font-size: large;"><span style="font-size: small;">error message - </span></span></b>сообщение об ошибке</span></span><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b><span style="font-size: large;"> </span></b></span></span></li>
</ul></div><div><span style="font-size: large;"><b style="font-family: Verdana,sans-serif;">F</b></span></div><ul style="color: black; text-align: left;"><li style="color: black;"><span style="font-size: large;"><b style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;">feature request ("запрос об улучшении") - </span></span></b><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;">"баг" рационализаторского плана</span></span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>file a bug - </b>рапортавать баг</span></span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>front-end - </b>это непосредственный интерфейс пользователя, т.е. текст, картинки, кнопки, линки и прочие вещи, которые видит пользователь </span></span></span></span></li>
<li style="color: black;"><b><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;">functional bug</span></span></b><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"> - функциональный баг</span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>fix - </b>починка, ремонт</span></span></li>
</ul><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>H</b></span></span></span></span></div><div style="color: black;"><ul style="text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-size: small;">HTML - </span></b><span style="font-size: small;">Hyper Text <span style="font-family: Verdana,sans-serif; font-size: small;">Markup Language</span><span style="font-family: Verdana,sans-serif;"> - </span></span></span></span></span></span><span style="font-family: Verdana,sans-serif; font-size: small;">стандартный язык разметки документов во Всемирной паутине</span></li>
<li><span style="color: black; font-family: Verdana,sans-serif; font-size: small;"><b>HTTP - </b>Hyper Text Transfer Protocol - </span><span style="color: black; font-size: small;"><span style="font-family: Verdana,sans-serif;">протокол </span></span><span style="color: black; font-family: Verdana,sans-serif; font-size: small;">прикладного уровня передачи данных (изначально&nbsp;— в виде гипертекстовых документов)</span><span style="font-family: Verdana,sans-serif; font-size: small;"> </span></li>
</ul><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>I</b></span></span></span></span></div><div style="color: black;"><ul style="color: black; text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-size: small;">input - </span></b><span style="font-size: small;">ввод</span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>invalid input - </b>ввод недействительных значений</span></span></span></span></span></li>
</ul><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>L</b></span></span></span></span></span></span></span><br>
<ul style="text-align: left;"><li><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>logical bug - </b>логический баг</span></span></span><b> </b></span></span></span></span></span></span></span></li>
</ul></div><div style="color: black; text-align: left;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-size: small;"></span></b></span></span></span></span></span></span></span></div><div style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b></b></span></span> </span></span></span></span></span><br>
<ul style="color: black; text-align: left;"></ul><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><b>M</b></span></span></span></span></span></span></div><div style="color: black;"><ul style="text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><b><span style="font-size: small;">maintainability - </span></b><span style="font-size: small;">поддерживаемость, т.е. насколько легко и просто можно изменить тест-кейс при изменениях в ПО</span></span></span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><span style="font-size: small;"><b>meeting - </b>совещание </span></span></span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><span style="font-size: small;"><b>modified - </b>измененный</span></span></span></span></span></span></span></li>
</ul><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"> </span></span></span></span></span><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><b>N</b></span></span></span></span></span></span></div><div style="color: black;"><ul style="text-align: left;"><li style="color: black;"><span style="font-family: Verdana,sans-serif;"><span style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b><a href="http://valyav.blogspot.com/2011/04/blog-post_01.html#more">"negative" testing</a> - </b>"негативное" тестирование - это тестирование на данных или сценариях, которые соответствуют нештатному поведению тестируемой системы - различные сообщения об ошибках, исключительные ситуации, "запредельные" состояния и т.д.</span></span></span></span><b style="font-family: Verdana,sans-serif;"><span style="font-size: 11pt; line-height: 115%;"><span style="font-size: small;"> </span></span></b></li>
<li style="color: black;"><b style="font-family: Verdana,sans-serif;"><span style="font-size: 11pt; line-height: 115%;"><span style="font-size: small;">new feature testing</span> - </span></b><span style="font-family: Verdana,sans-serif;"><span style="font-size: 11pt; line-height: 115%;">тестирование новых компонентов</span></span><b style="font-family: Verdana,sans-serif;"><span style="font-size: 11pt; line-height: 115%;"> </span></b><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><b><span style="font-size: small;">&nbsp;</span></b></span></span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><b><span style="font-size: small;">null input - </span></b><span style="font-size: small;">пустой ввод</span></span></span></span></span></span></span></li>
</ul><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><b> </b></span></span></span></span></span></span><br>
<span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>P</b></span></span></span></span></div><div style="color: black; text-align: left;"><ul style="color: black; text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-size: small;">performance testing - </span></b><span style="font-size: small;">тестирование скорости работы всей системы либо ее компонента</span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>pattern - </b>шаблон, тенденция</span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>procedure - </b>процедура - совокупность шагов в тест-кейсе</span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="color: black;"><span style="font-family: Verdana,sans-serif;"><b><a href="http://valyav.blogspot.com/2011/04/blog-post_01.html#more">"positive" testing</a> - </b>"позитивное" тестирование - это тестирование на данных или сценариях, которые соответствуют нормальному (штатному, ожидаемому) поведению тестируемой системы</span></span></span></span></span></span></span></li>
</ul></div><div style="color: black; text-align: left;"><ul style="color: black; text-align: left;"></ul><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><b>Q</b></span></span></span></span></span></span></div><div style="color: black; text-align: left;"><ul style="color: black; text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><b><span style="font-size: small;">QA (quality assurance) - </span></b><span style="font-size: small;">обеспечение качества - это забота о качестве в виде превентирования появления багов. QA призвано улучшить ПО через улучшение процесса разработки ПО</span></span></span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><span style="font-size: small;"><b>QA Engineer</b> - инженер по качеству</span></span></span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><span style="font-size: small;"><b>QA Knowledge Base - </b>Пособие для тестировщиков</span></span></span></span></span></span></span></li>
</ul></div><div style="color: black; text-align: left;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>R</b></span></span></div><div style="color: black; text-align: left;"><ul style="text-align: left;"><li><b style="color: black;"><span style="font-family: Verdana,sans-serif; font-size: small;"><span style="line-height: 115%;">regression testing - </span></span></b><span style="color: black; font-family: Verdana,sans-serif; font-size: small;"><span style="line-height: 115%;">регрессивное тестирование</span></span><i><span style="font-family: &quot;Calibri&quot;,&quot;sans-serif&quot;; font-size: 11pt; line-height: 115%;"> </span></i></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-size: small;">required fields - </span></b><span style="font-size: small;">обязательные поля</span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>release ("релиз") - </b>передача ПО пользователю&nbsp;</span></span></span></li>
</ul><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;">&nbsp;&nbsp;&nbsp;<i><b>&nbsp;&nbsp;&nbsp; <span style="font-size: small;">Классификация "релизообразных":</span></b></i></span></span></span></div><div style="color: black; text-align: left;"><span style="font-size: small;"><i><span style="font-family: Verdana,sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="font-family: Verdana,sans-serif;"><b>1.</b> <b>Релиз (он же основной релиз) (major release)</b> — стадия в цикле&nbsp; разработки ПО,идущая за стадией тестирования и ремонта багов, т.е.&nbsp; передача пользователям кода новой версии нашего ПО. Как правило,&nbsp; обозначается целыми числами, например 7.0.</span></i></span>  </div><div style="color: black; text-align: left;"><div class="MsoListParagraphCxSpMiddle" style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>2</b><b>. </b><b>Дополнительный релиз </b><b>(minor release)</b> — ситуация, когда&nbsp; после&nbsp; основного релиза планово выпускается новая функциональность или&nbsp; изменяется/удаляется старая. Дополнительный релиз не связан в багами. Как правило, обозначается десятыми, например 7.1.</i></span></div><div class="MsoListParagraphCxSpLast" style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><i>&nbsp;&nbsp;&nbsp;&nbsp; <b>3.</b> <b>Заплаточный релиз </b><b>(patch release)</b>, когда после обнаружения и &nbsp; ремонта бага выпускается исправленный код. Как правило, обозначается&nbsp; сотыми, например 7.11.</i></span><br>
<ul style="text-align: left;"><li style="color: black;"><b>release candidate </b>- сборка-кандидат на релиз</li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>retired - </b>более недействителен</span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>retired test cases - </b>недействительные тест-кейсы</span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>revision history - </b>история редактирования</span></span></span></li>
</ul></div></div><div style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>S</b></span></span></span></span><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><br>
</b></span></span></div><div style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"> </span></span></div><div style="color: black; text-align: left;"><ul style="text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>setup and additional info - </b>подготовительная часть</span></span></li>
<li style="color: black;"><b><span style="font-family: Verdana,sans-serif; font-size: small;"><span lang="EN-US" style="line-height: 115%;">smoke</span><span lang="EN-US" style="line-height: 115%;"> </span><span lang="EN-US" style="line-height: 115%;">test</span><span style="line-height: 115%;">, </span><span lang="EN-US" style="line-height: 115%;">sanity</span><span lang="EN-US" style="line-height: 115%;"> </span><span lang="EN-US" style="line-height: 115%;">test</span><span style="line-height: 115%;"> or </span><span lang="EN-US" style="line-height: 115%;">confidence</span><span lang="EN-US" style="line-height: 115%;"> </span><span lang="EN-US" style="line-height: 115%;">test</span><span lang="EN-US" style="line-height: 115%;"> -</span></span></b><span style="font-family: Symbol;"><span style="font: 7pt &quot;Times New Roman&quot;;">&nbsp; </span></span><span style="font-family: Verdana,sans-serif; font-size: small;">тест приемки (в процессе которого проверяются основные функциональности)  <span style="font-family: Verdana,sans-serif;"><span lang="EN-US" style="line-height: 115%;">&nbsp; </span></span></span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif; font-size: small;"><b><span lang="EN-US" style="line-height: 115%;">s</span><span style="line-height: 115%;">oftware development life</span><span style="line-height: 115%;"> </span><span style="line-height: 115%;">cycle</span></b></span><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"> <span style="font-family: Verdana,sans-serif;">-</span></span></span><span style="font-family: Verdana,sans-serif; font-size: small;"><span style="font-size-adjust: none; font-stretch: normal; font-style: normal; font-variant: normal; font-weight: normal; line-height: normal;"> </span>(процесс) разработки ПО — это путь от идеи до поддержки готового продукта.</span>  </li>
<li style="color: black;"><b><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;">spec</span></span></b><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"> - спецификация</span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>spec bug - </b>баг в спецификации</span></span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif; font-size: small;"><b><span style="line-height: 115%;">syntax bug</span></b></span><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"> - синтаксический баг </span></span></li>
</ul></div><div style="color: black; text-align: left;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>T</b></span></span></div><div style="color: black; text-align: left;"><ul style="text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>target group - </b>целевая аудитория</span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><b>Team Building Activities - </b>мероприятия по сплочению коллектива</span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-size: small;">testing - </span></b><span style="font-size: small;">тестирование - это забота о качестве в виде обнаружения багов до того как их найдут пользователи. Тестирование </span></span></span><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><span style="font-size: large;"><span style="font-size: small;">призвано улучшить ПО через обнаружение багов.</span></span></span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>Test Engineer - </b>тестировщик</span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>test case - </b>тест-кейс - </span></span></span>это артефакт, описывающий совокупность шагов, конкретных условий и  параметров, необходимых для проверки реализации тестируемой функции или  её части.             </li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>test case suite - </b>тест-комплекты, совокупность тест-кейсов</span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>test case generation - </b>создание тест-кейса</span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>test case execution - </b>исполнение тест-кейса</span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>test case result - </b>исход исполнения тест-кейса</span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-size: small;">test case priority - </span></b><span style="font-size: small;">приоритет тест-кейса</span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>test-coverage</b> - </span></span></span>это одна из метрик оценки качества тестирования, представляющая из себя  плотность покрытия тестами требований либо исполняемого кода.<span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"> </span></span></span></li>
<li style="color: black;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>test design </b>- </span></span></span>это этап процесса тестирования ПО, на котором проектируются и создаются  тестовые случаи (тест кейсы), в соответствии с определёнными ранее  критериями качества и целями тестирования.             <span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"> </span></span></span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif; font-size: small;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>test framing - </b>обоснование тестов</span></span></span><b><span style="line-height: 115%;">&nbsp;</span></b></span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif; font-size: small;"><b><span style="line-height: 115%;">testcase&nbsp; review - </span></b><span style="line-height: 115%;">рассмотрение тест-кейсов</span></span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif; font-size: small;"><span style="line-height: 115%;"><span style="color: black;"><b>test plan </b><span style="font-size: small;">- </span></span></span></span><span style="font-size: small;">это документ, описывающий весь объем работ по тестированию, начиная с  описания объекта, стратегии, расписания, критериев начала и окончания  тестирования, до необходимого в процессе работы оборудования,  специальных знаний, а также оценки рисков с вариантами их разрешения.</span><span style="font-family: Verdana,sans-serif; font-size: small;"><span style="line-height: 115%;"> </span></span></li>
<li style="color: black;"><span style="font-family: Verdana,sans-serif; font-size: small;"><span style="line-height: 115%;"><br>
</span></span></li>
</ul></div><div style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>U</b></span></span></span></span><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>&nbsp;</b></span></span></span></span></div><div style="color: black;"><ul style="color: black; text-align: left;"><li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-size: small;">upload - </span></b><span style="font-size: small;">загрузить</span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>unique ID - </b>уникальный ID</span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>unit-testing - </b>юнит-тестирование - это тестирование, производимое самим программистом </span></span></span></span></span></li>
<li style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"><b>URL (uniform resource locator) - </b>адрес файла в сети</span></span></span></span></span></li>
</ul><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b>V</b></span></span></span></span><br>
<ul style="text-align: left;"><li><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;">valid input - </span></span></span></b><span style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;">ввод действительных значений</span></span></span><b> </b></span></span></span></span></li>
</ul></div><div style="color: black; text-align: left;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><b><span style="font-size: small;"><br>
</span></b></span></span></span></span></div><div style="color: black;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: small;"></span></span></span></span></span><br>
<ul style="text-align: left;"></ul></div><div style="color: black; text-align: left;"><span style="font-size: small;"><span style="font-family: Verdana,sans-serif;"><span style="font-size: large;"><span style="font-family: Verdana,sans-serif;"><br>
</span></span></span></span></div><div style="text-align: left;"><br>
</div></div>
